<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

 <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.361">
      <PrivateAssets>none</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="MySqlConnector" Version="*" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="*" />
    <PackageReference Include="Dapper" Version="*" />
    <ProjectReference Include="..\ClientprefsApi\ClientprefsApi.csproj" />

  </ItemGroup>

  <ItemGroup>
    <None Update="lang\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>